// Generates src/web/astrofin-fonts.css from the woff2 files in
// resources/fonts/ (fetched by fetch-fonts.mjs, described by manifest.json).
//
// Every face is inlined as a `data:font/woff2;base64,...` URL: the sheet is
// injected into jellyfin-web, which is served from the *server's* origin, so a
// relative or app:// href would either 404 or trip the page's CSP. A data URL
// has no origin to cross.
//
// Run: node dev/tools/brand/build-fonts.mjs
//
// Importing this file does nothing: `main()` runs only when the file is the
// process entry point, so the unit tests can drive it against a temp dir.

import { readFileSync, writeFileSync, statSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, '../../..');
const FONTS = resolve(REPO, 'resources/fonts');
const OUT = resolve(REPO, 'src/web/astrofin-fonts.css');

// The sheet is injected into every page load, so it has a size budget.
export const MAX_BYTES = 600 * 1024;

export function version(m, family) {
    return m.faces.find((f) => f.family === family)?.version ?? 'unknown';
}

/** The whole stylesheet: the provenance header plus one @font-face per face. */
export function buildCss(manifest, fontsDir) {
    const head = `/* Astrofin web fonts — generated by dev/tools/brand/build-fonts.mjs.
 * DO NOT EDIT BY HAND. Re-run:
 *   node dev/tools/brand/fetch-fonts.mjs   # refresh resources/fonts/
 *   node dev/tools/brand/build-fonts.mjs   # regenerate this file
 *
 * Sources: Google Fonts, latin subset only, fetched ${manifest.fetchedAt}.
 * ${manifest.cssUrl}
 * Sora ${version(manifest, 'Sora')}, Inter ${version(manifest, 'Inter')}, IBM Plex Mono ${version(manifest, 'IBM Plex Mono')}.
 * All three are SIL Open Font License 1.1; the license texts ship alongside
 * the woff2 files in resources/fonts/<family>/OFL.txt.
 *
 * Sora and Inter are variable fonts, so one payload covers the whole weight
 * range the design uses; IBM Plex Mono ships as static instances.
 *
 * The faces are inlined as data: URLs so the sheet can be injected into a page
 * served from the Jellyfin server's origin without a cross-scheme font load.
 */
`;

    const blocks = manifest.faces.map((face) => {
        const abs = resolve(fontsDir, face.file);
        const bytes = readFileSync(abs);
        if (bytes.length !== face.bytes) {
            throw new Error(`${face.file}: manifest says ${face.bytes} bytes, file is ${bytes.length}`);
        }
        if (bytes.toString('ascii', 0, 4) !== 'wOF2') throw new Error(`${face.file} is not woff2`);
        const b64 = bytes.toString('base64');
        return `/* ${face.family} ${face.weight}${face.variable ? ' (variable)' : ''} — resources/fonts/${face.file} */
@font-face {
  font-family: '${face.family}';
  font-style: ${face.style};
  font-weight: ${face.weight};
  font-display: swap;
  src: url(data:font/woff2;base64,${b64}) format('woff2');
  unicode-range: ${face.unicodeRange};
}`;
    });

    return head + '\n' + blocks.join('\n\n') + '\n';
}

export function main(options = {}) {
    const fontsDir = options.fontsDir || FONTS;
    const out = options.out || OUT;
    const manifest = JSON.parse(readFileSync(resolve(fontsDir, 'manifest.json'), 'utf8'));

    writeFileSync(out, buildCss(manifest, fontsDir));

    const size = statSync(out).size;
    console.log(`wrote src/web/astrofin-fonts.css — ${manifest.faces.length} faces, ${size} bytes (${(size / 1024).toFixed(1)} KiB)`);
    for (const f of manifest.faces) {
        console.log(`  ${f.family.padEnd(14)} ${String(f.weight).padEnd(9)} ${String(f.bytes).padStart(6)} B woff2`);
    }
    if (size > MAX_BYTES) throw new Error(`generated CSS is ${size} bytes — over the 600 KB budget`);
    return { out, size, faces: manifest.faces.length };
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
    main();
}
