// Unit tests for the web-font CSS generator. Run with:
//
//     node --test dev/tools/brand/build-fonts.test.mjs
//
// (or `just test-js`). What matters about this script is that the sheet it
// writes is honest: every face comes from a file the manifest describes, the
// bytes are checked against the manifest before they are inlined, and anything
// that is not a woff2 is refused rather than base64'd into the page.
//
// Nothing here downloads a font or touches resources/: the tests build a
// throwaway font directory under os.tmpdir() and point the script at it.
import test from 'node:test';
import assert from 'node:assert';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { resolve, join } from 'node:path';

import { version, buildCss, main, MAX_BYTES } from './build-fonts.mjs';

// A woff2 file is only ever identified by its 'wOF2' magic here.
function woff2(size = 32) {
    const buf = Buffer.alloc(size, 0x41);
    buf.write('wOF2', 0, 4, 'ascii');
    return buf;
}

function face(over = {}) {
    return Object.assign({
        family: 'Sora',
        weight: '200 400',
        style: 'normal',
        variable: true,
        file: 'sora/Sora-Variable.woff2',
        bytes: 32,
        version: 'v14',
        source: 'https://fonts.gstatic.com/s/sora/v14/x.woff2',
        unicodeRange: 'U+0000-00FF'
    }, over);
}

// A temp resources/fonts/ with a manifest and the files it describes.
function fontsDir(t, faces) {
    const dir = mkdtempSync(join(tmpdir(), 'astrofin-fonts-'));
    t.after(() => rmSync(dir, { recursive: true, force: true }));
    const manifest = {
        fetchedAt: '2026-09-09',
        cssUrl: 'https://fonts.googleapis.com/css2?family=Sora',
        userAgent: 'test',
        license: 'OFL-1.1',
        faces
    };
    for (const f of faces) {
        mkdirSync(resolve(dir, f.file, '..'), { recursive: true });
        writeFileSync(resolve(dir, f.file), woff2(f.bytes));
    }
    writeFileSync(resolve(dir, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n');
    return { dir, manifest };
}

function quiet(t) {
    const lines = [];
    const real = console.log;
    console.log = (...args) => lines.push(args.join(' '));
    t.after(() => { console.log = real; });
    return lines;
}

test('version reads a family version out of the manifest', () => {
    const manifest = { faces: [face({ family: 'Inter', version: 'v18' }), face()] };
    assert.strictEqual(version(manifest, 'Inter'), 'v18');
    assert.strictEqual(version(manifest, 'Sora'), 'v14');
});

test('version says unknown for a family that is not there', () => {
    assert.strictEqual(version({ faces: [] }, 'Sora'), 'unknown');
    assert.strictEqual(version({ faces: [face({ version: undefined })] }, 'Sora'), 'unknown');
});

test('buildCss writes the provenance header from the manifest', (t) => {
    const { dir, manifest } = fontsDir(t, [face()]);
    const css = buildCss(manifest, dir);
    assert.match(css, /generated by dev\/tools\/brand\/build-fonts\.mjs/);
    assert.match(css, /DO NOT EDIT BY HAND/);
    assert.match(css, /fetched 2026-09-09/);
    assert.match(css, /Sora v14, Inter unknown, IBM Plex Mono unknown/);
    assert.match(css, /SIL Open Font License 1\.1/);
});

test('buildCss inlines each face as a base64 data URL', (t) => {
    const { dir, manifest } = fontsDir(t, [face()]);
    const css = buildCss(manifest, dir);
    const b64 = woff2(32).toString('base64');
    assert.match(css, /@font-face \{/);
    assert.ok(css.includes(`src: url(data:font/woff2;base64,${b64}) format('woff2');`), css);
    assert.ok(css.includes("font-family: 'Sora';"));
    assert.ok(css.includes('font-weight: 200 400;'));
    assert.ok(css.includes('font-display: swap;'));
    assert.ok(css.includes('unicode-range: U+0000-00FF;'));
});

test('buildCss labels a variable face and leaves a static one plain', (t) => {
    const faces = [
        face(),
        face({
            family: 'IBM Plex Mono', weight: '400', variable: false,
            file: 'ibm-plex-mono/IBMPlexMono-400.woff2'
        })
    ];
    const { dir, manifest } = fontsDir(t, faces);
    const css = buildCss(manifest, dir);
    assert.match(css, /\/\* Sora 200 400 \(variable\) — resources\/fonts\/sora\/Sora-Variable\.woff2 \*\//);
    assert.match(css, /\/\* IBM Plex Mono 400 — resources\/fonts\/ibm-plex-mono\/IBMPlexMono-400\.woff2 \*\//);
    assert.strictEqual(css.match(/@font-face/g).length, 2);
    assert.ok(css.endsWith('}\n'), 'exactly one trailing newline');
});

test('buildCss refuses a file whose size disagrees with the manifest', (t) => {
    const { dir, manifest } = fontsDir(t, [face()]);
    writeFileSync(resolve(dir, manifest.faces[0].file), woff2(64));
    assert.throws(
        () => buildCss(manifest, dir),
        /Sora-Variable\.woff2: manifest says 32 bytes, file is 64/
    );
});

test('buildCss refuses a file that is not woff2', (t) => {
    const { dir, manifest } = fontsDir(t, [face()]);
    writeFileSync(resolve(dir, manifest.faces[0].file), Buffer.alloc(32, 0x41));
    assert.throws(() => buildCss(manifest, dir), /is not woff2/);
});

test('buildCss fails loudly when a described file is missing', (t) => {
    const { dir, manifest } = fontsDir(t, [face()]);
    rmSync(resolve(dir, manifest.faces[0].file));
    assert.throws(() => buildCss(manifest, dir), /ENOENT/);
});

test('main writes the sheet and reports what went into it', (t) => {
    const { dir } = fontsDir(t, [face(), face({
        family: 'Inter', weight: '400 600', file: 'inter/Inter-Variable.woff2', version: 'v18'
    })]);
    const out = join(dir, 'astrofin-fonts.css');
    const logged = quiet(t);
    const result = main({ fontsDir: dir, out });

    assert.strictEqual(result.faces, 2);
    const css = readFileSync(out, 'utf8');
    assert.strictEqual(result.size, Buffer.byteLength(css));
    assert.strictEqual(css.match(/@font-face/g).length, 2);
    assert.match(logged[0], /wrote src\/web\/astrofin-fonts\.css — 2 faces/);
    assert.strictEqual(logged.length, 3, 'a summary line and one per face');
});

test('main refuses to ship a sheet over the size budget', (t) => {
    const big = MAX_BYTES; // base64 of it is ~4/3 the size, so the sheet is over
    const { dir } = fontsDir(t, [face({ bytes: big })]);
    const out = join(dir, 'astrofin-fonts.css');
    quiet(t);
    assert.throws(() => main({ fontsDir: dir, out }), /over the 600 KB budget/);
});

test('importing the module runs nothing', async () => {
    // A second import must not write a file or print anything; the guard at the
    // bottom only fires when the script is the process entry point.
    const before = console.log;
    const mod = await import('./build-fonts.mjs');
    assert.strictEqual(console.log, before);
    assert.strictEqual(typeof mod.main, 'function');
});
